"use client";

import { useActionState, useState, useTransition } from "react";

import { FormAlert, fieldErrorsFor } from "@/components/forms/form-alert";
import { SubmitButton } from "@/components/forms/submit-button";
import { Button } from "@/components/ui/button";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import type { ActionResult } from "@/lib/errors";

import {
  startTotpEnrollmentAction,
  type TotpEnrollment,
  verifyTotpEnrollmentAction,
} from "../actions";

/**
 * TOTP enrolment: start → scan QR (or type the key) → confirm a code.
 * The secret is shown once, only to the signed-in user, and never logged.
 */
export function MfaEnrollment({ next }: { next?: string | undefined }) {
  const [enrollment, setEnrollment] = useState<ActionResult<TotpEnrollment> | null>(null);
  const [starting, startTransition] = useTransition();
  const [verifyState, verifyAction] = useActionState(verifyTotpEnrollmentAction, null);

  if (!enrollment?.ok) {
    return (
      <div className="flex flex-col gap-3">
        <FormAlert state={enrollment} />
        <Button
          className="w-fit"
          loading={starting}
          onClick={() =>
            startTransition(async () => setEnrollment(await startTotpEnrollmentAction()))
          }
        >
          Set up authenticator app
        </Button>
      </div>
    );
  }

  const { factorId, qrCode, secret } = enrollment.data;
  return (
    <div className="flex flex-col gap-4">
      <ol className="flex list-decimal flex-col gap-2 pl-5 text-sm text-muted-foreground">
        <li>
          Open an authenticator app (for example Microsoft Authenticator or Google Authenticator).
        </li>
        <li>Scan the QR code, or enter the setup key manually.</li>
        <li>Enter the 6-digit code the app shows.</li>
      </ol>
      {/* eslint-disable-next-line @next/next/no-img-element -- data: URI SVG generated by Supabase Auth */}
      <img
        src={qrCode}
        alt="QR code for your authenticator app"
        width={180}
        height={180}
        className="rounded-md border border-border bg-surface p-2"
      />
      <p className="text-sm">
        Setup key:{" "}
        <code
          data-testid="totp-secret"
          className="rounded-sm bg-surface-muted px-1.5 py-0.5 font-mono break-all"
        >
          {secret}
        </code>
      </p>
      <form action={verifyAction} className="flex max-w-sm flex-col gap-4" noValidate>
        <FormAlert state={verifyState} />
        <input type="hidden" name="factorId" value={factorId} />
        <input type="hidden" name="next" value={next ?? ""} />
        <FormField
          id="code"
          label="Authentication code"
          required
          errors={fieldErrorsFor(verifyState, "code")}
        >
          <Input name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} />
        </FormField>
        <SubmitButton className="w-fit">Confirm and enable</SubmitButton>
      </form>
    </div>
  );
}
