/**
 * Payroll preparation and invoice drafting vocabulary (P0-E7-S2).
 *
 * Preparation, not execution: nothing here pays a worker, sends an invoice,
 * calculates tax or collects payment. Every amount is integer minor units
 * copied by the database from immutable priced lines; this module only labels
 * states and checks export integrity.
 */
import { Constants, type Database } from "@/types/database.types";

type Enums = Database["public"]["Enums"];

export type PayrollBatchStatus = Enums["payroll_batch_status"];
export type InvoiceDraftStatus = Enums["invoice_draft_status"];
export type PayrollPeriodType = Enums["payroll_period_type"];

export const PAYROLL_BATCH_STATUSES = Constants.public.Enums.payroll_batch_status;
export const INVOICE_DRAFT_STATUSES = Constants.public.Enums.invoice_draft_status;
export const PAYROLL_PERIOD_TYPES = Constants.public.Enums.payroll_period_type;

export const PAYROLL_PERIOD_TYPE_LABELS: Record<PayrollPeriodType, string> = {
  weekly: "Weekly",
  biweekly: "Every two weeks",
};

export const PAYROLL_BATCH_STATUS_LABELS: Record<PayrollBatchStatus, string> = {
  draft: "Draft",
  reviewed: "Reviewed",
  approved: "Approved",
  locked: "Locked",
  exported: "Exported",
  cancelled: "Cancelled",
};

export const INVOICE_DRAFT_STATUS_LABELS: Record<InvoiceDraftStatus, string> = {
  draft: "Draft",
  reviewed: "Reviewed",
  approved: "Approved",
  locked: "Locked",
  exported: "Exported",
  voided: "Voided",
};

export type StatusTone = "neutral" | "info" | "success" | "warning" | "danger" | "brand";

/** Status → badge tone. Teal (brand) is reserved for the approved/locked states. */
export function financialStatusTone(status: PayrollBatchStatus | InvoiceDraftStatus): StatusTone {
  switch (status) {
    case "draft":
      return "neutral";
    case "reviewed":
      return "info";
    case "approved":
    case "locked":
      return "brand";
    case "exported":
      return "success";
    default:
      return "neutral";
  }
}

export const ATTENTION_LABELS: Record<string, string> = {
  SOURCE_SUPERSEDED: "Includes revised work",
  ADJUSTMENT_REQUIRED: "Adjustment required",
  PRICING_REQUIRED: "Not priced yet",
};

export function attentionLabel(code: string | null | undefined): string | null {
  if (!code) return null;
  return ATTENTION_LABELS[code] ?? code;
}

export const RECONCILIATION_STATES = [
  "unprepared",
  "adjustment_required",
  "drafted",
  "approved",
  "exported",
] as const;
export type ReconciliationState = (typeof RECONCILIATION_STATES)[number];

export const RECONCILIATION_LABELS: Record<ReconciliationState, string> = {
  unprepared: "Not yet prepared",
  adjustment_required: "Adjustment required",
  drafted: "In a draft",
  approved: "Approved or locked",
  exported: "Exported",
};

export const PAYROLL_CSV_COLUMNS = [
  "batch_reference",
  "worker_reference",
  "worker_name",
  "period_start",
  "period_end",
  "work_date",
  "facility",
  "discipline",
  "regular_minutes",
  "overtime_minutes",
  "pay_rate_minor",
  "pay_amount_minor",
  "currency",
] as const;

export const INVOICE_CSV_COLUMNS = [
  "invoice_draft_reference",
  "facility",
  "relationship_reference",
  "period_start",
  "period_end",
  "work_date",
  "worker_reference",
  "worker_name",
  "discipline",
  "priced_minutes",
  "bill_rate_minor",
  "bill_amount_minor",
  "currency",
] as const;

/** A SHA-256 hex digest, as stored on every export record. */
export function isSha256Hex(value: string): boolean {
  return /^[0-9a-f]{64}$/.test(value);
}

/** Short display form of a checksum: first and last 8 hex digits. */
export function shortChecksum(sha256: string): string {
  return isSha256Hex(sha256) ? `${sha256.slice(0, 8)}…${sha256.slice(-8)}` : sha256;
}

/**
 * Export file names are generated by the database from the document
 * reference ([A-Z0-9-] plus extension). Anything else is refused rather than
 * escaped, so a header can never be injected through Content-Disposition.
 */
export function safeExportFileName(fileName: string): string | null {
  return /^[A-Z0-9][A-Z0-9-]{0,80}\.(csv|pdf)$/.test(fileName) ? fileName : null;
}

export function formatByteSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
